### ISSUE TITLE
Exception thrown if empty string is passed to any of the methods

### ISSUE THREAD

**Issue by natintosh** [emostar/flutter-libphonenumber#10]
```
E/flutter ( 6944): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: PlatformException(NumberParseException, The string supplied did not seem to be a phone number., null)
E/flutter ( 6944): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:569:7)
E/flutter ( 6944): #1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:321:33)
E/flutter ( 6944): <asynchronous suspension>
E/flutter ( 6944): #2      PhoneNumberUtil.normalizePhoneNumber (package:libphonenumber/libphonenumber.dart:36:27)
E/flutter ( 6944): #3      _MyHomePageState.setValue (package:intl_helper_test/main.dart:53:31)
E/flutter ( 6944): #4      _MyHomePageState.build.<anonymous closure> (package:intl_helper_test/main.dart:45:15)
E/flutter ( 6944): #5      new TextFormField.<anonymous closure>.onChangedHandler (package:flutter/src/material/text_form_field.dart:160:20)
E/flutter ( 6944): #6      EditableTextState._formatAndSetValue (package:flutter/src/widgets/editable_text.dart:1607:14)
E/flutter ( 6944): #7      EditableTextState.updateEditingValue (package:flutter/src/widgets/editable_text.dart:1208:5)
E/flutter ( 6944): #8      TextInput._handleTextInputInvocation (package:flutter/src/services/text_input.dart:965:36)
E/flutter ( 6944): #9      MethodChannel._handleAsMethodCall (package:flutter/src/services/platform_channel.dart:402:55)
E/flutter ( 6944): #10     MethodChannel.setMethodCallHandler.<anonymous closure> (package:flutter/src/services/platform_channel.dart:370:54)
E/flutter ( 6944): #11     _DefaultBinaryMessenger.handlePlatformMessage (package:flutter/src/services/binding.dart:200:33)
E/flutter ( 6944): #12     _invoke3.<anonymous closure> (dart:ui/hooks.dart:303:15)
E/flutter ( 6944): #13     _rootRun (dart:async/zone.dart:1126:13)
E/flutter ( 6944): #14     _CustomZone.run (dart:async/zone.dart:1023:19)
E/flutter ( 6944): #15     _CustomZone.runGuarded (dart:async/zone.dart:925:7)
E/flutter ( 6944): #16     _invoke3 (dart:ui/hooks.dart:302:10)
E/flutter ( 6944): #17     _dispatchPlatformMessage (dart:ui/hooks.dart:162:5)
E/flutter ( 6944): 
```

**Comment by emostar** [comment]
Related to #15
