### ISSUE TITLE
 java.lang.IllegalStateException: Reply already submitted

### ISSUE THREAD

**Issue by michael-ottink** [emostar/flutter-libphonenumber#20]
I have the following service

```
class ContactsService with ChangeNotifier {
  LoadingState _state = LoadingState.uninitialized;
  List<MobileContactModel> _mobileContacts = List<MobileContactModel>();

  LoadingState get state => _state;
  List<MobileContactModel> get mobileContacs => _mobileContacts.toList();

  ContactsService() {
    refreshContacts();
  }

  Future<void> refreshContacts() async {
    bool hasPermission = await Permission.contacts.request().isGranted;

    if (!hasPermission) {
      _state = LoadingState.permissionDenied;
      notifyListeners();
    }

    _state = LoadingState.loading;
    notifyListeners();

    List<MobileContactModel> rawContacts = (await contactsService.ContactsService.getContacts(withThumbnails: false))
        .where((contact) => contact.phones.any((iterable) => iterable.label == 'mobile'))
        .map((contact) => MobileContactModel(
            contact.displayName, contact.phones.firstWhere((phoneNumber) => phoneNumber.label == 'mobile').value))
        .toList();

    _mobileContacts = await validateContacts(rawContacts);

    _state = LoadingState.loaded;
    notifyListeners();
  }

  Future<List<MobileContactModel>> validateContacts(List<MobileContactModel> rawContacts) async {
    List<Future<MobileContactModel>> validations = List<Future<MobileContactModel>>();

    for (MobileContactModel rawContact in rawContacts) validations.add(_validateContact(rawContact));

    var test = (await Future.wait(validations)).toList();
    test.removeWhere((value) => value == null);
    return test;
  }

  Future<MobileContactModel> _validateContact(MobileContactModel rawContact) async {
    return await _isValidMobileNumber(rawContact.phonenumber) ? rawContact : null;
  }

  Future<bool> _isValidMobileNumber(String phoneNumber) async {
    if (phoneNumber.isEmpty) return false;

    try {
      PhoneNumberType type = await PhoneNumberUtil.getNumberType(phoneNumber: phoneNumber, isoCode: 'NL');
      return type == PhoneNumberType.mobile;
    } catch (error) {
      return false;
    }
  }
}
```

But the _isValidMobileNumber() keeps throwing the following error. Is there a way to catch this error? Is there anything I can do about this? Or is it an error that's in the package?

```
E/MethodChannel#codeheadlabs.com/libphonenumber(13840): Failed to handle method call
E/MethodChannel#codeheadlabs.com/libphonenumber(13840): java.lang.IllegalStateException: Reply already submitted
E/MethodChannel#codeheadlabs.com/libphonenumber(13840):         at io.flutter.embedding.engine.dart.DartMessenger$Reply.reply(DartMessenger.java:148)
E/MethodChannel#codeheadlabs.com/libphonenumber(13840):         at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler$1.success(MethodChannel.java:234)
E/MethodChannel#codeheadlabs.com/libphonenumber(13840):         at com.codeheadlabs.libphonenumber.LibphonenumberPlugin.formatAsYouType(LibphonenumberPlugin.java:157)
E/MethodChannel#codeheadlabs.com/libphonenumber(13840):         at com.codeheadlabs.libphonenumber.LibphonenumberPlugin.onMethodCall(LibphonenumberPlugin.java:44)
E/MethodChannel#codeheadlabs.com/libphonenumber(13840):         at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:231)
E/MethodChannel#codeheadlabs.com/libphonenumber(13840):         at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:93)
E/MethodChannel#codeheadlabs.com/libphonenumber(13840):         at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:642)
E/MethodChannel#codeheadlabs.com/libphonenumber(13840):         at android.os.MessageQueue.nativePollOnce(Native Method)
E/MethodChannel#codeheadlabs.com/libphonenumber(13840):         at android.os.MessageQueue.next(MessageQueue.java:336)
E/MethodChannel#codeheadlabs.com/libphonenumber(13840):         at android.os.Looper.loop(Looper.java:174)
E/MethodChannel#codeheadlabs.com/libphonenumber(13840):         at android.app.ActivityThread.main(ActivityThread.java:7356)
E/MethodChannel#codeheadlabs.com/libphonenumber(13840):         at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#codeheadlabs.com/libphonenumber(13840):         at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
E/MethodChannel#codeheadlabs.com/libphonenumber(13840):         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
E/DartMessenger(13840): Uncaught exception in binary message listener
E/DartMessenger(13840): java.lang.IllegalStateException: Reply already submitted
E/DartMessenger(13840):         at io.flutter.embedding.engine.dart.DartMessenger$Reply.reply(DartMessenger.java:148)
E/DartMessenger(13840):         at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:249)
E/DartMessenger(13840):         at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:93)
E/DartMessenger(13840):         at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:642)
E/DartMessenger(13840):         at android.os.MessageQueue.nativePollOnce(Native Method)
E/DartMessenger(13840):         at android.os.MessageQueue.next(MessageQueue.java:336)
E/DartMessenger(13840):         at android.os.Looper.loop(Looper.java:174)
E/DartMessenger(13840):         at android.app.ActivityThread.main(ActivityThread.java:7356)
E/DartMessenger(13840):         at java.lang.reflect.Method.invoke(Native Method)
E/DartMessenger(13840):         at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
E/DartMessenger(13840):         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
```
I am using the latest Flutter version and libphonenumber: ^1.0.1

**Comment by natintosh** [comment]
There is a bug with `PhoneNumberUtil.getNumberType`, but a PR #19 fixed it, I hope he publishes an update soon

**Comment by emostar** [comment]
Should be fixed now, please update to the latest version (1.0.2 as of this moment)
