### ISSUE TITLE
Error When Using The Lib in Flutter For Web

### ISSUE THREAD

**Issue by febiyan** [emostar/flutter-libphonenumber#22]
I am using a library that depends on this libphonenumber library. When I run my app on the web browser, on localhost, I've been getting MissingPluginException errors coming from libphonenumber library. I have no issues with native apps.

pubspec.yaml:
`
international_phone_input: ^1.0.4
`

Error:
`
Error: MissingPluginException(No implementation found for method isValidPhoneNumber on channel codeheadlabs.com/libphonenumber)
    at Object.throw_ [as throw] (http://localhost:54687/dart_sdk.js:4773:11)
    at MethodChannel._invokeMethod (http://localhost:54687/packages/flutter/src/services/platform_channel.dart.lib.js:398:21)
`

Is there anything I can do to circumvent this?

**Comment by kateile** [comment]
I think you need some if statement to check what platform is running. Since I think this lib have no yet web implementation

**Comment by Yacine-Benali** [comment]
am having the same issue any updates ?

**Comment by emostar** [comment]
As @kateile said, this does not support web yet. Pull requests are welcome, as it may be faster for someone else to add it, than wait for me.

**Comment by cedvdb** [comment]
@emostar Support for web platform already exists https://github.com/natintosh/plugin_libphonenumber

**Comment by dorsamet** [comment]
Is there a plan to merge this in at some point?

**Comment by cedvdb** [comment]
@dorsamet there is this cross platform library  https://pub.dev/packages/phone_numbers_parser

It's a rewrite of libphonenumber on android
