### ISSUE TITLE
Getting MissingPluginException

### ISSUE THREAD

**Issue by codingedward** [emostar/flutter-libphonenumber#6]
I tried using the package as shown in the example provided:
```dart
bool isValid = await PhoneNumberUtil.isValidPhoneNumber(
  phoneNumber: phoneNumber,
  isoCode: countryCode
);
```

However, the following exception is thrown:
```
E/flutter ( 3423): [ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: MissingPluginException(No implementation found for method isValidPhoneNumber on channel codeheadlabs.com/libphonenumber)
E/flutter ( 3423): #0      MethodChannel.invokeMethod 
package:flutter/…/services/platform_channel.dart:314
E/flutter ( 3423): <asynchronous suspension>
E/flutter ( 3423): #1      PhoneNumberUtil.isValidPhoneNumber  (package:libphonenumber/libphonenumber.dart:26:27)
E/flutter ( 3423): <asynchronous suspension>
E/flutter ( 3423): #2      PhoneNumberFormatService.isValid 
package:whatsapp/services/phone_number_format_service.dart:13
E/flutter ( 3423): <asynchronous suspension>
E/flutter ( 3423): #3      _SignUpState._onNext 
package:whatsapp/…/signup/signup.dart:93
E/flutter ( 3423): <asynchronous suspension>
E/flutter ( 3423): #4      _SignUpState.build.<anonymous closure> 
package:whatsapp/…/signup/signup.dart:209
E/flutter ( 3423): #5      _InkResponseState._handleTap 
package:flutter/…/material/ink_well.dart:635
E/flutter ( 3423): #6      _InkResponseState.build.<anonymous closure> 
package:flutter/…/material/ink_well.dart:711
E/flutter ( 3423): #7      GestureRecognizer.invokeCallback 
package:flutter/…/gestures/recognizer.dart:182
E/flutter ( 3423): #8      TapGestureRecognizer._checkUp 
package:flutter/…/gestures/tap.dart:365
E/flutter ( 3423): #9      TapGestureRecognizer.handlePrimaryPointer 
package:flutter/…/gestures/tap.dart:275
E/flutter ( 3423): #10     PrimaryPointerGestureRecognizer.handleEvent 
package:flutter/…/gestures/recognizer.dart:455
E/flutter ( 3423): #11     PointerRouter._dispatch 
package:flutter/…/gestures/pointer_router.dart:75
E/flutter ( 3423): #12     PointerRouter.route 
package:flutter/…/gestures/pointer_router.dart:102
E/flutter ( 3423): #13     _WidgetsFlutterBinding&BindingBase&GestureBinding.handleEvent 
package:flutter/…/gestures/binding.dart:218
E/flutter ( 3423): #14     _WidgetsFlutterBinding&BindingBase&GestureBinding.dispatchEvent 
package:flutter/…/gestures/binding.dart:198
E/flutter ( 3423): #15     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerEvent 
package:flutter/…/gestures/binding.dart:156
E/flutter ( 3423): #16     _WidgetsFlutterBinding&BindingBase&GestureBinding._flushPointerEventQueue 
package:flutter/…/gestures/binding.dart:102
E/flutter ( 3423): #17     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerDataPacket 
package:flutter/…/gestures/binding.dart:86
E/flutter ( 3423): #18     _rootRunUnary  (dart:async/zone.dart:1136:13)
E/flutter ( 3423): #19     _CustomZone.runUnary  (dart:async/zone.dart:1029:19)
E/flutter ( 3423): #20     _CustomZone.runUnaryGuarded  (dart:async/zone.dart:931:7)
E/flutter ( 3423): #21     _invoke1  (dart:ui/hooks.dart:250:10)
E/flutter ( 3423): #22     _dispatchPointerDataPacket  (dart:ui/hooks.dart:159:5)
E/flutter ( 3423):
```

**Comment by codingedward** [comment]
This fixed it. 

https://github.com/flutter/flutter/issues/10912

Thanks for this wonderful plugin!!! 👍 🎊
